version: '3.8'

services:
  calculator:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

